#spring.datasource.url=jdbc:mysql://localhost:3306/applestore?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.cache=false
#

#deploy web

spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
